/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoswing;

import java.text.ParseException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Jonas
 */
public class FrameComponentes extends javax.swing.JFrame {
    MaskFormatter mascara_cpf;
    MaskFormatter mascara_cnpj;
    /**
     * Creates new form FrameComponentes
     */
    public FrameComponentes() {
        initComponents();
        getMascara_CNPJ();
        getMascara_CPF();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        tbGuias = new javax.swing.JTabbedPane();
        pnPrimeiraAba = new javax.swing.JPanel();
        btnExibirMensagem = new javax.swing.JButton();
        btnExibirPergunta = new javax.swing.JButton();
        pnSplitPane = new javax.swing.JPanel();
        spPane = new javax.swing.JSplitPane();
        pnTesteCb = new javax.swing.JPanel();
        cbDias = new javax.swing.JComboBox<>();
        cbCategorias = new javax.swing.JComboBox<>();
        btnIncluirDias = new javax.swing.JButton();
        btnIncluirCategorias = new javax.swing.JButton();
        lblCategoria = new javax.swing.JLabel();
        pnTesteTable = new javax.swing.JPanel();
        pnTesteRadio = new javax.swing.JPanel();
        rdFisico = new javax.swing.JRadioButton();
        rdJuridico = new javax.swing.JRadioButton();
        txtCPFCNPJ = new javax.swing.JFormattedTextField();
        lblcpfcnpj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbGuias.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        btnExibirMensagem.setText("Exibir Mensagem");
        btnExibirMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirMensagemActionPerformed(evt);
            }
        });

        btnExibirPergunta.setText("Exibir Pergunta");
        btnExibirPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirPerguntaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPrimeiraAbaLayout = new javax.swing.GroupLayout(pnPrimeiraAba);
        pnPrimeiraAba.setLayout(pnPrimeiraAbaLayout);
        pnPrimeiraAbaLayout.setHorizontalGroup(
            pnPrimeiraAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrimeiraAbaLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(pnPrimeiraAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExibirPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExibirMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        pnPrimeiraAbaLayout.setVerticalGroup(
            pnPrimeiraAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrimeiraAbaLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnExibirMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnExibirPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        tbGuias.addTab("Primeira Aba", pnPrimeiraAba);

        javax.swing.GroupLayout pnSplitPaneLayout = new javax.swing.GroupLayout(pnSplitPane);
        pnSplitPane.setLayout(pnSplitPaneLayout);
        pnSplitPaneLayout.setHorizontalGroup(
            pnSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSplitPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spPane, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnSplitPaneLayout.setVerticalGroup(
            pnSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSplitPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spPane, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbGuias.addTab("Teste SplitPane", pnSplitPane);

        cbDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Exibir Dias" }));
        cbDias.setName(""); // NOI18N

        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Exibir Categorias" }));
        cbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriasActionPerformed(evt);
            }
        });

        btnIncluirDias.setText("Incluir Dias");
        btnIncluirDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirDiasActionPerformed(evt);
            }
        });

        btnIncluirCategorias.setText("Incluir Categorias");
        btnIncluirCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirCategoriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTesteCbLayout = new javax.swing.GroupLayout(pnTesteCb);
        pnTesteCb.setLayout(pnTesteCbLayout);
        pnTesteCbLayout.setHorizontalGroup(
            pnTesteCbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTesteCbLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(pnTesteCbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbDias, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCategorias, javax.swing.GroupLayout.Alignment.LEADING, 0, 197, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnTesteCbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIncluirCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(btnIncluirDias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );
        pnTesteCbLayout.setVerticalGroup(
            pnTesteCbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTesteCbLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(pnTesteCbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIncluirDias))
                .addGap(79, 79, 79)
                .addGroup(pnTesteCbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIncluirCategorias))
                .addGap(18, 18, 18)
                .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        tbGuias.addTab("Teste ComboBox", pnTesteCb);

        javax.swing.GroupLayout pnTesteTableLayout = new javax.swing.GroupLayout(pnTesteTable);
        pnTesteTable.setLayout(pnTesteTableLayout);
        pnTesteTableLayout.setHorizontalGroup(
            pnTesteTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        pnTesteTableLayout.setVerticalGroup(
            pnTesteTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        tbGuias.addTab("Teste JTable", pnTesteTable);

        buttonGroup.add(rdFisico);
        rdFisico.setSelected(true);
        rdFisico.setText("Físico");
        rdFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFisicoActionPerformed(evt);
            }
        });

        buttonGroup.add(rdJuridico);
        rdJuridico.setText("Juridico");
        rdJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdJuridicoActionPerformed(evt);
            }
        });

        lblcpfcnpj.setText("CPF:");

        javax.swing.GroupLayout pnTesteRadioLayout = new javax.swing.GroupLayout(pnTesteRadio);
        pnTesteRadio.setLayout(pnTesteRadioLayout);
        pnTesteRadioLayout.setHorizontalGroup(
            pnTesteRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTesteRadioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnTesteRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTesteRadioLayout.createSequentialGroup()
                        .addComponent(rdFisico)
                        .addGap(48, 48, 48)
                        .addComponent(rdJuridico))
                    .addGroup(pnTesteRadioLayout.createSequentialGroup()
                        .addComponent(lblcpfcnpj)
                        .addGap(18, 18, 18)
                        .addComponent(txtCPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        pnTesteRadioLayout.setVerticalGroup(
            pnTesteRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTesteRadioLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnTesteRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdFisico)
                    .addComponent(rdJuridico))
                .addGap(59, 59, 59)
                .addGroup(pnTesteRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcpfcnpj))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        tbGuias.addTab("Teste JRadioButton", pnTesteRadio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(tbGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(tbGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExibirMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirMensagemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, //posição-centro da tela
                                            "Mensagem", //mensagem
                                            "Titulo da Mensagem", 
                                            JOptionPane.ERROR_MESSAGE);// tipo INFORMATION_MESSAGE
    }//GEN-LAST:event_btnExibirMensagemActionPerformed

    private void btnExibirPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirPerguntaActionPerformed
        // TODO add your handling code here:
        int retorno = JOptionPane.showConfirmDialog(null, 
                                                        "Mensagem",
                                                        "Titulo da Mensagem",
                                                        JOptionPane.YES_NO_CANCEL_OPTION,
                                                        JOptionPane.QUESTION_MESSAGE);
        
        switch(retorno){
            case 0:
                JOptionPane.showMessageDialog(null, "Clicou SIM");
                break;
            case 1:
                JOptionPane.showMessageDialog(null, "Clicou NÃO");
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Clicou CANCEL");
                break;
            default:
                  System.out.println(retorno);  
        }
    }//GEN-LAST:event_btnExibirPerguntaActionPerformed

    private void btnIncluirDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirDiasActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("Domingo");
        modelo.addElement("Segunda");
        modelo.addElement("Terça");
        modelo.addElement("Quarta");
        modelo.addElement("Quinta");
        modelo.addElement("Sexta");
        modelo.addElement("Sábado");
        cbDias.setModel(modelo);
    }//GEN-LAST:event_btnIncluirDiasActionPerformed

    private void btnIncluirCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirCategoriasActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        Categorias c1 = new Categorias();
        c1.setId(1);
        c1.setDescricao("Informática");
        modelo.addElement(c1);
        Categorias c2 = new Categorias();
        c2.setId(2);
        c2.setDescricao("Celulares");
        modelo.addElement(c2);
        cbCategorias.setModel(modelo);
    }//GEN-LAST:event_btnIncluirCategoriasActionPerformed

    private void cbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriasActionPerformed
        // TODO add your handling code here:
        Categorias c = (Categorias) cbCategorias.getSelectedItem();//cast para Categoria
        lblCategoria.setText(c.getId() + " - " + c.getDescricao());
    }//GEN-LAST:event_cbCategoriasActionPerformed

    private void rdFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFisicoActionPerformed
        // TODO add your handling code here:
        lblcpfcnpj.setText("CPF:");
        mascara_cpf.install(txtCPFCNPJ);
        txtCPFCNPJ.requestFocus();
    }//GEN-LAST:event_rdFisicoActionPerformed

    private void rdJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdJuridicoActionPerformed
        // TODO add your handling code here:
        lblcpfcnpj.setText("CNPJ:");
        mascara_cnpj.install(txtCPFCNPJ);
        txtCPFCNPJ.requestFocus();
    }//GEN-LAST:event_rdJuridicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameComponentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExibirMensagem;
    private javax.swing.JButton btnExibirPergunta;
    private javax.swing.JButton btnIncluirCategorias;
    private javax.swing.JButton btnIncluirDias;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox<String> cbCategorias;
    private javax.swing.JComboBox<String> cbDias;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblcpfcnpj;
    private javax.swing.JPanel pnPrimeiraAba;
    private javax.swing.JPanel pnSplitPane;
    private javax.swing.JPanel pnTesteCb;
    private javax.swing.JPanel pnTesteRadio;
    private javax.swing.JPanel pnTesteTable;
    private javax.swing.JRadioButton rdFisico;
    private javax.swing.JRadioButton rdJuridico;
    private javax.swing.JSplitPane spPane;
    private javax.swing.JTabbedPane tbGuias;
    private javax.swing.JFormattedTextField txtCPFCNPJ;
    // End of variables declaration//GEN-END:variables

    private MaskFormatter getMascara_CPF(){
        mascara_cpf = new MaskFormatter();
        try{
            mascara_cpf.setMask("###.###.###-##");
            mascara_cpf.setPlaceholderCharacter('_');
        } catch(ParseException e){
            e.printStackTrace();
        }
        return mascara_cpf;
    }
    
    private MaskFormatter getMascara_CNPJ(){
        if(mascara_cnpj == null){
            mascara_cnpj = new MaskFormatter();
            try{
                mascara_cnpj.setMask("##.###.###/####-##");
                mascara_cnpj.setPlaceholderCharacter('_');
            } catch(ParseException e){
                e.printStackTrace();
            }
        }
        return mascara_cnpj;
    }

}
